config/routes.rb
Rails.application.routes.draw do
  root "static_pages#top"
  # ユーザー処理
  resources :users, only: %i[new create show edit update]
  resource :mypage, only: %i[show edit update]
  # 投稿一覧、投稿作成
  resources :posts, only: %i[index new create show edit update destroy]
  # カテゴリーページ
  resources :categories, only: %i[show], param: :category
  resources :drinks, only: %i[show]
  # ログインアウト処理
  get "login", to: "user_sessions#new"
  post "login", to: "user_sessions#create"
  delete "logout", to: "user_sessions#destroy"
  delete "/logout", to: "user_sessions#destroy"
  # Google認証
  get "/auth/:provider/callback", to: "user_sessions#google_auth"
  get "/auth/failure", to: redirect("/")
  # 管理者専用設定
  namespace :admin do
    resources :drinks, only: %i[index new create edit update]
  end
  # Drinkのブックマーク設定
  resources :bookmarks, only: %i[create destroy]
  resources :drinks, only: %i[index new create show edit update destroy] do
    collection do
      get :bookmarks
    end
  end
  # 利用規約、プライバシーポリシー
  get "pages/privacy_policy", to: "pages#privacy_policy", as: "privacy_policy"
  get "pages/terms_of_service", to: "pages#terms_of_service", as: "terms_of_service"
end

app/models/drink.rb
class Drink < ApplicationRecord
  mount_uploader :drink_image, DrinkImageUploader

  validates :name, presence: true
  validates :description, presence: true, length: { maximum: 250 }
  validates :alcohol, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 100 }
  validates :drink_image, presence: true
  validates :category_id, presence: true

  belongs_to :user
  belongs_to :category
  has_many :bookmarks, dependent: :destroy

  ransack_alias :alcohol_eq, :alcohol
  ransack_alias :category_id_eq, :category_id

  # 日本語表示用のヘルパーを追加
  def category_name
    category&.name || '不明'
  end

  def self.ransackable_attributes(auth_object = nil)
    ["id", "name", "description", "alcohol", "category_id", "created_at", "updated_at", "user_id", "mixing_instructions", "drink_image"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["category"]
  end
end

app/controllers/admin/drinks_controller.rb
module Admin
  class Admin::DrinksController < ApplicationController
    before_action :require_admin
    before_action :set_categories, only: [:new, :create, :edit]
    skip_before_action :require_login, only: %i[index]

    def new
      @drink = Drink.new
    end

    def index
      @drinks = Drink.all.page(params[:page]).per(20)
      render "drinks/index"
    end

    def create
      @drink = current_user.drinks.new(drink_params)
      @drink.is_admin = true

      category = Category.find_by(id: params[:drink][:category_id])
      @drink.category = category if category.present?

      if @drink.save
        redirect_to category_path(@drink.category.name), success: "新しいドリンクが追加されました。"
      else
        flash.now[:alert] = @drink.errors.full_messages.join(", ")
        render :new, status: :unprocessable_entity
      end
    end

    def edit
      @drink = Drink.find(params[:id])
    end

    def update
      @drink = Drink.find(params[:id])
      
      if @drink.update(drink_params)
        redirect_to category_path(@drink.category.name), success: "ドリンク情報が更新されました。"
      else
        flash.now[:alert] = @drink.errors.full_messages.join(", ")
        render :edit, status: :unprocessable_entity
      end
    end

    private

    def set_categories
      @categories = Category.all
    end

    def drink_params
      params.require(:drink).permit(:name, :description, :alcohol, :drink_image, :mixing_instructions, :category_id)
    end

    def require_admin
      unless current_user&.is_admin?
        redirect_to root_path, alert: "管理者のみアクセス可能です。"
      end
    end
  end
end

app/controllers/drinks_controller.rb
class DrinksController < ApplicationController
  before_action :set_drink, only: %i[show destroy]

  def index
    @q = Drink.ransack(params[:q])
    @drinks = @q.result(distinct: true)
    @drinks = [] if @drinks.nil?
    search_keyword = params.dig(:q, :name_or_description_or_mixing_instructions_cont)
    category_id = params.dig(:q, :category_id_eq) # 選択されたカテゴリーID
    category_name = category_id.present? ? Category.find_by(id: category_id)&.name : nil
    if search_keyword.present?
      @rakuten_items = RakutenApi.search_items(search_keyword, category_name)
    else
      @rakuten_items = []
    end
  end
  
  def show
    @drink = Drink.find(params[:id])
    @bookmarked_drinks = current_user.bookmarked_drinks || []
  end

  # 削除処理
  def destroy
    @drink.destroy
    redirect_to drinks_url, success: 'ドリンクが削除されました。'
  end

  # ブックマーク
  def bookmarks
    @bookmark_drinks = current_user.bookmarked_drinks.includes(:user).order(created_at: :desc)
  end

  private

  def set_drink
    @drink = Drink.find(params[:id])
  end

  def drink_params
    params.require(:drink).permit(:name, :description, :alcohol, :mixing_instructions, :image)
  end
end

app/helpers/admin/drinks_helper.rb
module Admin::DrinksHelper
end

app/helpers/drinks_helper.rb
module DrinksHelper
end

app/views/admin/drinks/edit.html.erb
<div class="container mx-auto pt-5">
    <div class="max-w-4xl mx-auto mt-3 z-20">
      <h1 class="text-2xl font-bold mb-3 mt-3">ドリンクの編集</h1>

      <%= form_with model: @drink, url: admin_drink_path(@drink), local: true do |form| %>
        <div class="mb-4">
          <%= form.label :name, "ドリンク名", class: "block text-sm font-medium text-gray-700" %>
          <%= form.text_field :name, class: "mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500" %>
        </div>

        <div class="mb-4">
          <%= form.label :description, "説明", class: "block text-sm font-medium text-gray-700" %>
          <%= form.text_area :description, rows: 3, class: "mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500" %>
        </div>

        <div class="mb-4">
          <%= form.label :alcohol, "アルコール度数", class: "block text-sm font-medium text-gray-700" %>
          <%= form.number_field :alcohol, step: :any, class: "mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500" %>
        </div>

        <div class="mb-4">
          <%= form.label :drink_image, "ドリンク画像", class: "block text-sm font-medium text-gray-700" %>
          <%= form.file_field :drink_image, class: "mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500" %>
        </div>

        <div class="mb-4">
          <%= form.label :mixing_instructions, "作り方", class: "block text-sm font-medium text-gray-700" %>
          <%= form.text_area :mixing_instructions, rows: 4, class: "mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500" %>
        </div>

        <div class="mb-4">
            <%= form.label :category_id, "カテゴリー", class: "block text-sm font-medium text-gray-700" %>
            <%= form.collection_select :category_id, @categories, :id, :name, prompt: "カテゴリーを選択", class: "mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500" %>
        </div>

        <div class="mb-4">
          <%= form.submit "更新する", class: "inline-flex items-center px-4 py-2 border border-transparent text-lg font-medium rounded-md shadow-sm text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
        </div>
      <% end %>
    </div>
</div>

app/views/admin/drinks/new.html.erb
<div class="container mx-auto pt-5">
    <div class="max-w-4xl mx-auto mt-3 z-20">
      <h1 class="text-2xl font-bold mb-3 mt-3">新しいドリンクの追加</h1>

      <%= form_with model: @drink, url: admin_drinks_path, local: true do |form| %>
        <div class="mb-4">
          <%= form.label :name, "ドリンク名", class: "block text-sm font-medium text-gray-700" %>
          <%= form.text_field :name, class: "mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500" %>
        </div>

        <div class="mb-4">
          <%= form.label :description, "説明", class: "block text-sm font-medium text-gray-700" %>
          <%= form.text_area :description, rows: 3, class: "mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500" %>
        </div>

        <div class="mb-4">
          <%= form.label :alcohol, "アルコール度数", class: "block text-sm font-medium text-gray-700" %>
          <%= form.number_field :alcohol, step: :any, class: "mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500" %>
        </div>

        <div class="mb-4">
          <%= form.label :drink_image, "ドリンク画像", class: "block text-sm font-medium text-gray-700" %>
          <%= form.file_field :drink_image, class: "mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500" %>
        </div>

        <div class="mb-4">
          <%= form.label :mixing_instructions, "作り方", class: "block text-sm font-medium text-gray-700" %>
          <%= form.text_area :mixing_instructions, rows: 4, class: "mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500" %>
        </div>

        <div class="mb-4">
          <% if @categories.present? %>
            <%= form.label :category_id, "カテゴリー", class: "block text-sm font-medium text-gray-700" %>
            <%= form.collection_select :category_id, @categories, :id, :name, prompt: "カテゴリーを選択", class: "mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500" %>
          <% else %>
            <p>カテゴリーがありません</p>
          <% end %>
        </div>

        <div class="mb-4">
          <%= form.submit "追加", class: "inline-flex items-center px-4 py-2 border border-transparent text-lg font-medium rounded-md shadow-sm text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
        </div>
      <% end %>
    </div>
</div>