config/routes.rb
Rails.application.routes.draw do
  root "static_pages#top"
  # ユーザー処理
  resources :users, only: %i[new create show edit update]
  resource :mypage, only: %i[show edit update]
  # 投稿一覧、投稿作成
  resources :posts, only: %i[index new create show edit update destroy]
  # カテゴリーページ
  resources :categories, only: %i[show], param: :category
  resources :drinks, only: %i[show]
  # ログインアウト処理
  get "login", to: "user_sessions#new"
  post "login", to: "user_sessions#create"
  delete "logout", to: "user_sessions#destroy"
  delete "/logout", to: "user_sessions#destroy"
  # Google認証
  get "/auth/:provider/callback", to: "user_sessions#google_auth"
  get "/auth/failure", to: redirect("/")
  # 管理者専用設定
  namespace :admin do
    resources :drinks, only: %i[index new create edit update]
  end
  # Drinkのブックマーク設定
  resources :bookmarks, only: %i[create destroy]
  resources :drinks, only: %i[index new create show edit update destroy] do
    collection do
      get :bookmarks
    end
  end
  # 利用規約、プライバシーポリシー
  get "pages/privacy_policy", to: "pages#privacy_policy", as: "privacy_policy"
  get "pages/terms_of_service", to: "pages#terms_of_service", as: "terms_of_service"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/authentication.rb
class Authentication < ApplicationRecord
  belongs_to :user
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  validates :user_id, uniqueness: { scope: :drink_id }

  belongs_to :user
  belongs_to :drink
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts
  has_many :drinks

  ransack_alias :name_cont, :name

  def display_name
    translations = {
      "beer" => "ビール",
      "wine" => "ワイン",
      "nihonshu" => "日本酒",
      "shochu" => "焼酎",
      "cocktail" => "カクテル",
      "etc" => "その他"
    }
    translations[name] || name # 該当する名前がない場合はそのまま返す
  end

  def category_name
    case name
    when "ビール"
      "ビール"
    when "ワイン"
      "ワイン"
    when "日本酒"
      "日本酒"
    when "焼酎"
      "焼酎"
    when "カクテル"
      "カクテル"
    when "etc"
      "その他"
    else
      "不明"
    end
  end
end

app/models/drink.rb
class Drink < ApplicationRecord
  mount_uploader :drink_image, DrinkImageUploader

  validates :name, presence: true
  validates :description, presence: true, length: { maximum: 250 }
  validates :alcohol, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 100 }
  validates :drink_image, presence: true
  validates :category_id, presence: true

  belongs_to :user
  belongs_to :category
  has_many :bookmarks, dependent: :destroy

  ransack_alias :alcohol_eq, :alcohol
  ransack_alias :category_id_eq, :category_id

  # 日本語表示用のヘルパーを追加
  def category_name
    category&.name || '不明'
  end

  def self.ransackable_attributes(auth_object = nil)
    ["id", "name", "description", "alcohol", "category_id", "created_at", "updated_at", "user_id", "mixing_instructions", "drink_image"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["category"]
  end
end

app/models/post.rb
class Post < ApplicationRecord
  # 値が空でないこと・最大30文字以下であること
  validates :title, presence: { message: "を入力してください" }, length: { maximum: 30, message: "は30文字以内で入力してください" }
  # 値が空でないこと・最大250文字以下であること
  validates :body, presence: { message: "を入力してください" }, length: { maximum: 250, message: "は270文字以内で入力してください" }
  # 画像が投稿されていること
  validates :post_image_url, presence: true

  belongs_to :user
  mount_uploader :post_image, PostImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  # 値が空でないこと・最大100文字以下であること
  validates :name, presence: { message: "を入力してください" }, length: { maximum:100 }
  # 値が空でないこと・ユニークな値であること
  validates :email, presence: { message: "を入力してください" }, uniqueness: true
  # 最低3文字以上必要
  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  # password_confirmation と一致すること
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  # 値が空でないこと（nilや空文字でない）
  validates :password_confirmation, presence: { message: "を入力してください" }, if: -> { new_record? || changes[:crypted_password] }
  # Googleログインの場合はpasswordを仮に設定する（パスワードのバリデーションをスキップ）
  validates :password, presence: true, if: -> { new_record? && crypted_password.blank? }
  validates :password_confirmation, presence: true, if: -> { password.present? }
  # 属性の値が一意であり重複していないこと（nil は除く）
  validates :reset_password_token, uniqueness: true, allow_nil: true
  # Googleログイン用
  validates :google_uid, uniqueness: true, allow_nil: true

  has_many :drinks, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :bookmarked_drinks, through: :bookmarks, source: :drink

  def own?(object)
    id == object&.user_id
  end

  # ブックマーク処理
  def bookmark(drink)
    bookmarked_drinks << drink
  end

  def unbookmark(drink)
    bookmarked_drinks.destroy(drink)
  end

  def bookmark?(drink)
    bookmarked_drinks.include?(drink)
  end

  # 管理者かどうか判定する
  def admin?
    is_admin
  end

  # Googleログイン時のユーザー検索または作成
  def self.find_or_create_from_google(auth)
    user = find_by(google_uid: auth["uid"])

    unless user
      user = find_by(email: auth["info"]["email"])
      if user
        user.update(google_uid: auth["uid"])
      else
        user = User.new(
          name: auth["info"]["name"],
          email: auth["info"]["email"],
          google_uid: auth["uid"],
          password: SecureRandom.hex(10)
        )
        user.password_confirmation = user.password
        user.save(validate: false)
      end
    end

    user
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :require_login
  def privacy_policy
  end

  def terms_of_service
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_ogp, only: [:show]

  def index
    @posts = Post.includes(:user).page(params[:page]).per(20)
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)

    Rails.logger.info "post_params: #{post_params.inspect}"

    if @post.save
      redirect_to posts_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @post = Post.find_by(id: params[:id])
    if @post.nil?
      flash[:aleat] = "お探しの投稿はありません"
      redirect_to posts_path
    end
  end

  def edit
    @post = current_user.posts.find(params[:id])
  end

  def update
    @post = current_user.posts.find(params[:id])
    if @post.update(post_params)
      redirect_to post_path(@post), success: "投稿を更新しました"
    else
      flash.now[:danger] = "更新出来ませんでした"
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    post = current_user.posts.find(params[:id])
    post.destroy!
    redirect_to posts_path, success: "投稿を削除しました", status: :see_other
  end

    private

  def post_params
    params.require(:post).permit(:title, :body, :post_image, :post_image_cache)
  end

  def set_ogp
    @post = Post.find(params[:id])
    @ogp = {
      title: @post.title,
      description: @post.body.truncate(100),
      image: @post.post_image.url || asset_path("default-ogp.png"),
      url: request.original_url
    }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # カテゴリーごとのパスを定義
  def category_path(category)
    category.present? ? category_url(category) : categories_path
  end

  def default_meta_tags
    {
      site: 'DrinkCollection',
      title: '新たなお酒との出会い',
      reverse: true,
      charset: 'utf-8',
      separator: '|',
      description: 'お酒好きや興味のある方にぴったりのwebアプリ!',
      keywords: 'お酒,飲み物,バー,カクテル,ビール',
      canonical: 'https://drinkcollection-1.onrender.com',
      noindex: !Rails.env.production?,
      
      og: {
        site_name: 'DrinkCollection',
        title: 'DrinkCollection',
        description: 'お酒好きや興味のある方にぴったりのwebアプリ!',
        type: 'website',
        url: 'https://drinkcollection-1.onrender.com',
        image: image_url('ogp-image.png'),
        locale: 'ja_JP',
      },

      twitter: {
        card: 'summary_large_image',
        site: '@snowflowerhaku',
        title: 'DrinkCollection',
        description: 'お酒好きや興味のある方にぴったりのwebアプリ!',
        image: image_url('ogp-image.png')
      }
    }
  end
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/drinks_helper.rb
module DrinksHelper
end

app/helpers/mypages_helper.rb
module MypagesHelper
end

app/helpers/oauths_helper.rb
module OauthsHelper
end

app/helpers/ogp_helper.rb
module OgpHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>DrinkCollection</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <%= display_meta_tags(default_meta_tags) %>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>

    <meta property="og:title" content="DrinkCollection - お酒の掲示板">
    <meta property="og:description" content="お酒の情報を共有し、あなたにぴったりの一杯を見つけよう！">
    <meta property="og:image" content="<%= image_url('default-ogp.png') %>">
    <meta property="og:url" content="<%= request.original_url %>">
    <meta property="og:type" content="website">
  </head>

  <body>
    <% if logged_in? %>
      <%= render "shared/header" %>
    <% else %>
      <%= render "shared/before_login_header" %>
    <% end %>
    <%= render "shared/flash_message" %>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/privacy_policy.html.erb
<div class="max-w-4xl mx-auto px-4">
  <h1 class="text-4xl text-center font-semibold mt-4 mb-4">プライバシーポリシー</h1>

  <h2 class="text-2xl text-center font-semibold mt-6 mb-4">ユーザーから取得する情報</h2>
  <p class="text-lg mb-4">本サービスは、ユーザーから以下の情報を取得します。</p>
  <p class="list-disc pl-6 mb-4">
    <li>氏名（ニックネームやペンネームも含む</li>
    <li>メールアドレス</li>
    <li>写真</li>
    <li>外部サービスでユーザーが利用するID、その他外部サービスのプライバシー設定によりユーザーが連携先に開示を認めた情報</li>
    <li>本サービスの滞在時間、入力履歴等の本サービスにおけるユーザーの行動履歴</li>
  </p>
  <br>

  <h2 class="text-2xl text-center font-semibold mt-6 mb-4">ユーザーの情報を利用する目的</h2>
  <p class="text-lg mb-4">本サービスは、ユーザーから取得した情報を、以下の目的のために利用します。</p>
  <p class="list-disc pl-6 mb-4">
    <li>本サービスに関する登録の受付、ユーザーの本人確認、認証のため</li>
    <li>ユーザーの本サービスの利用履歴を管理するため</li>
    <li>本サービスにおけるユーザーの行動履歴を分析し、本サービスの維持改善に役立てるため</li>
    <li>広告の配信、表示及び効果測定のため</li>
    <li>ユーザーからのお問い合わせに対応するため</li>
    <li>本サービスの規約や法令に違反する行為に対応するため</li>
    <li>本サービスの変更、提供中止、終了、契約解除のご連絡をするため</li>
    <li>本サービス規約の変更を通知するため</li>
    <li>以上の他、本サービスの提供、維持、保護及び改善のため</li>
  </p>
  <br>

  <h2 class="text-2xl text-center font-semibold mt-6 mb-4">第三者提供</h2>
    <p class="text-lg mb-4">本サービスは、ユーザーから取得する情報のうち、個人データ（個人情報保護法第16条第3項）に該当するものについては、あらかじめユーザーの同意を得ずに、第三者（日本国外にある者を含みます。）に提供しません。</p>
    <p class="text-lg mb-4">但し、次の場合は除きます。</p>
    <p class="list-disc pl-6 mb-4">
      <li>個人データの取扱いを外部に委託する場合</li>
      <li>本サービスが買収された場合</li>
      <li>事業パートナーと共同利用する場合（具体的な共同利用がある場合は、その内容を別途公表します。）</li>
      <li>その他、法律によって合法的に第三者提供が許されている場合</li>
    </p>
    <br>

  <h2 class="text-2xl text-center font-semibold mt-6 mb-4">アクセス解析ツール</h2>
  <p class="text-lg mb-4">本サービスは、ユーザーのアクセス解析のために、「Googkeアナリティクス」を利用しています。Googleアナリティクスは、トラフィックデータの収集のためにCookieを使用しています。トラフィックデータは匿名で収集されており、個人を特定する者ではありません。Cookieを無効にすれば、これらの情報の収集を拒否することができます。詳しくはお使いのブラウザの設定をご確認ください。Googleアナリティクスについて、詳しくは以下からご確認ください。</p>
  <p class="text-lg mb-4">https://marketingplatform.google.com/about/analytics/terms/jp/</p>
  <br>

  <h2 class="text-2xl text-center font-semibold mt-6 mb-4">広告の配信</h2>
    <p class="text-lg mb-4">本サービスは、以下のアフィリエイトプログラムに参加しています。そのため、第三者がコンテンツおよび宣伝を提供したり、訪問者から直接情報を収集し、訪問者のブラウザにCookieを設定したり、Cookieを認識したりする場合があります。</p>
    <p class="list-disc pl-6 mb-4">
      <li>Rakuten API：楽天が提供する商品やサービスの広告を配信しています。</li>
      <li>Link-AG：株式会社L&E Groupが提供するサービスの広告を配信しています。</li>
    </p>
    <br>

  <h2 class="text-2xl text-center font-semibold mt-6 mb-4">お問い合わせ</h2>
    <p class="text-lg mb-4">ユーザー情報の開示、情報の訂正、利用停止、削除をご希望の場合は、お問い合わせフォームよりご連絡ください。</p>
</div>

app/views/shared/_before_login_header.html.erb
<div class="pt-16"></div>
<header class="fixed top-0 left-0 w-full bg-amber-300 text-black z-20">
  <div class="container mx-auto px-4 py-4 flex items-center justify-between">
    <!-- ロゴ (常にトップページに遷移) -->
    <div class="flex space-x-6">
      <%= link_to "DrinkCollection", root_path, class: "text-2xl font-bold" %>

      <!-- ナビゲーション(画面サイズに関わらず常に表示) -->
      <nav class="flex mt-1 space-x-4">
        <%= link_to "ビール", category_path("beer"), class: "hover:invert" %>
        <%= link_to "ワイン", category_path("wine"), class: "hover:invert" %>
        <%= link_to "日本酒", category_path("nihonshu"), class: "hover:invert" %>
        <%= link_to "焼酎", category_path("shochu"), class: "hover:invert" %>
        <%= link_to "カクテル", category_path("cocktail"), class: "hover:invert" %>
        <%= link_to category_path("etc"), class: "hover:invert" do %>
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="h-6 w-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="M6.75 12a.75.75 0 1 1-1.5 0 .75.75 0 0 1 1.5 0ZM12.75 12a.75.75 0 1 1-1.5 0 .75.75 0 0 1 1.5 0ZM18.75 12a.75.75 0 1 1-1.5 0 .75.75 0 0 1 1.5 0Z" />
          </svg>
        <% end %>
      </nav>
    </div>

    <!-- 検索フォーム -->
    <div class="search-bar">
      <%= search_form_for @q, url: drinks_path, method: :get, html: { class: "search-form" } do |form| %>
        <div class="search-inputs">
          <!-- 名前検索 -->
          <%= form.text_field :name_or_description_or_mixing_instructions_cont, placeholder: "ドリンク名", class: "search-input px-4 py-2 border border-gray-300 rounded" %>
          <!-- 最低度数のプルダウン -->
          <%= form.select :alcohol_gteq, options_for_select([["0%以上", 0.0], ["1%以上", 1.0], ["5%以上", 5.0], ["10%以上", 10.0], ["15%以上", 15.0], ["20%以上", 20.0], ["30%以上", 30.0], ["40%以上", 40.0], ["50%以上", 50.0]], params.dig(:q, :alcohol_gteq)), prompt: "最低度数" %>
          <!-- 最高度数のプルダウン -->
          <%= form.select :alcohol_lteq, options_for_select([["5%以下", 5.0], ["10%以下", 10.0], ["15%以下", 15.0], ["20%以下", 20.0], ["30%以下", 30.0], ["40%以下", 40.0], ["50%以下", 50.0], ["60%以下", 60.0], ["70%以下", 70.0], ["80%以下", 80.0], ["90%以下", 90.0], ["100%以下", 100.0]], params.dig(:q, :alcohol_lteq)), prompt: "最高度数" %>
          <!-- カテゴリー選択 -->
          <%= form.select :category_id_eq, options_for_select(Category.order(:id).map { |c| [c.display_name, c.id] }, selected: params.dig(:q, :category_id_eq)), prompt: "カテゴリー" %>
          <!-- 検索ボタン -->
          <%= form.submit "検索", class: "search-btn bg-indigo-600 hover:bg-indigo-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
        </div>
      <% end %>
    </div>

    <div class="text-black z-50 relative">
      <div class="dropdown dropdown-bottom dropdown-left">
        <div tabindex="0" role="button" class="btn btn-ghost btn-circle">
          <!-- ハンバーガーアイコン -->
          <svg
            xmlns="http://www.w3.org/2000/svg"
            class="h-6 w-6"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
              d="M4 6h16M4 12h16M4 18h16" />
          </svg>
        </div>
        <ul tabindex="0" class="menu menu-sm dropdown-content mt-3 z-[1] p-2 shadow bg-white rounded-box w-40 text-base">
          <li>
            <%= link_to "新規登録", new_user_path, class: "text-black" %>
          </li>
          <li>
            <%= link_to t("header.login"), login_path, class: "text-black" %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</header>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation" class="bg-red-100 border border-red-400 text-red-700 p-4">
    <ul class="list-disc pl-5">
      <% object.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<!-- フラッシュメッセージ -->
<% flash.each do |message_type, message| %>
  <div class="mt-4 p-4 text-sm text-white
    <%= message_type == 'success' ? 'bg-green-500' : 'bg-red-500' %>">
    <%= message %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="bottom-0 left-0 w-full bg-amber-300 text-black py-6 z-20">
  <div class="container mx-auto">
    <div class="flex justify-center">
      <div class="text-center">
        <div class="flex space-x-8">
          <%= link_to "プライバシーポリシー", privacy_policy_path, class: "hover:text-gray" %>
          <%= link_to "利用規約", terms_of_service_path, class: "hover:text-gray" %>
          <%= link_to "お問い合わせフォーム", "https://docs.google.com/forms/d/e/1FAIpQLScXiicxf00SoabnSg_vEb7bptlGdfDS042CqiuBzKh03PRSfQ/viewform?usp=header", class: "hover:text-gray" %>
          <%= link_to "管理者専用ページ", new_admin_drink_path, class: "hover:text-gray" %>
        </div>
        <div class="mt-4">
          <p class="text-xs text-black">Copyright © 2025. DrinkCollection - All right reserved</p>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<div class="pt-16"></div>
<header class="fixed top-0 left-0 w-full bg-amber-300 text-black z-20">
  <div class="container mx-auto px-4 py-4 flex items-center justify-between">
    <!-- ロゴ (常にトップページに遷移) -->
    <div class="flex space-x-6">
      <%= link_to "DrinkCollection", root_path, class: "text-2xl font-bold" %>

      <!-- ナビゲーション(画面サイズに関わらず常に表示) -->
      <nav class="flex mt-1 space-x-4">
        <%= link_to "ビール", category_path(Category.find_by(name: "ビール").id), class: "hover:invert" %>
        <%= link_to "ワイン", category_path(Category.find_by(name: "ワイン").id), class: "hover:invert" %>
        <%= link_to "日本酒", category_path(Category.find_by(name: "日本酒").id), class: "hover:invert" %>
        <%= link_to "焼酎", category_path(Category.find_by(name: "焼酎").id), class: "hover:invert" %>
        <%= link_to "カクテル", category_path(Category.find_by(name: "カクテル").id), class: "hover:invert" %>
        <%= link_to category_path(Category.find_by(name: "etc").id), class: "hover:invert" do %>
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="h-6 w-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="M6.75 12a.75.75 0 1 1-1.5 0 .75.75 0 0 1 1.5 0ZM12.75 12a.75.75 0 1 1-1.5 0 .75.75 0 0 1 1.5 0ZM18.75 12a.75.75 0 1 1-1.5 0 .75.75 0 0 1 1.5 0Z" />
          </svg>
        <% end %>
      </nav>
    </div>

    <!-- 検索フォーム -->
    <div class="search-bar">
      <%= search_form_for @q, url: drinks_path, method: :get, html: { class: "search-form" } do |form| %>
        <div class="search-inputs">
          <!-- 名前検索 -->
          <%= form.text_field :name_or_description_or_mixing_instructions_cont, placeholder: "ドリンク名", class: "search-input px-4 py-2 border border-gray-300 rounded" %>
          <!-- 最低度数のプルダウン -->
          <%= form.select :alcohol_gteq, options_for_select([["0%以上", 0.0], ["1%以上", 1.0], ["5%以上", 5.0], ["10%以上", 10.0], ["15%以上", 15.0], ["20%以上", 20.0], ["30%以上", 30.0], ["40%以上", 40.0], ["50%以上", 50.0]], params.dig(:q, :alcohol_gteq)), prompt: "最低度数" %>
          <!-- 最高度数のプルダウン -->
          <%= form.select :alcohol_lteq, options_for_select([["5%以下", 5.0], ["10%以下", 10.0], ["15%以下", 15.0], ["20%以下", 20.0], ["30%以下", 30.0], ["40%以下", 40.0], ["50%以下", 50.0], ["60%以下", 60.0], ["70%以下", 70.0], ["80%以下", 80.0], ["90%以下", 90.0], ["100%以下", 100.0]], params.dig(:q, :alcohol_lteq)), prompt: "最高度数" %>
          <!-- カテゴリー選択 -->
          <%= form.select :category_id_eq, options_for_select(Category.order(:id).map { |c| [c.display_name, c.id] }, selected: params.dig(:q, :category_id_eq)), prompt: "カテゴリー" %>
          <!-- 検索ボタン -->
          <%= form.submit "検索", class: "search-btn bg-indigo-600 hover:bg-indigo-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
        </div>
      <% end %>
    </div>

    <!-- ハンバーガーメニュー（DaisyUI） -->
    <div class="text-black z-50 relative">
      <div class="dropdown dropdown-left dropdown-bottom">
        <!-- ハンバーガーアイコン -->
        <div tabindex="0" role="button" class="btn btn-ghost btn-circle">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
              d="M4 6h16M4 12h16M4 18h16" />
          </svg>
        </div>

        <!-- メニュー項目 -->
        <ul tabindex="0" class="menu menu-sm dropdown-content mt-3 z-[1] p-2 shadow bg-white rounded-box w-40 text-base">
          <li>
            <%= link_to t("header.create_post"), new_post_path, class: "text-black hover:bg-gray-100" %>
          </li>
          <li>
            <%= link_to t("header.post_index"), posts_path, class: "text-black hover:bg-gray-100" %>
          </li>
          <li>
            <%= link_to t("header.my_page"), mypage_path, class: "text-black hover:bg-gray-100" %>
          </li>
          <li>
            <%= link_to t("header.logout"), logout_path, method: :delete, data: { turbo_method: "delete" },
                  class: "text-black hover:bg-gray-100" %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</header>