config/routes.rb
Rails.application.routes.draw do
  root "static_pages#top"
  # ユーザー処理
  resources :users, only: %i[new create show edit update]
  resource :mypage, only: %i[show edit update]
  # 投稿一覧、投稿作成
  resources :posts, only: %i[index new create show edit update destroy]
  # カテゴリーページ
  resources :categories, only: %i[show], param: :category
  resources :drinks, only: %i[show]
  # ログインアウト処理
  get "login", to: "user_sessions#new"
  post "login", to: "user_sessions#create"
  delete "logout", to: "user_sessions#destroy"
  delete "/logout", to: "user_sessions#destroy"
  # Google認証
  get "/auth/:provider/callback", to: "user_sessions#google_auth"
  get "/auth/failure", to: redirect("/")
  # 管理者専用設定
  namespace :admin do
    resources :drinks, only: %i[index new create edit update]
  end
  # Drinkのブックマーク設定
  resources :bookmarks, only: %i[create destroy]
  resources :drinks, only: %i[index new create show edit update destroy] do
    collection do
      get :bookmarks
    end
  end
  # 利用規約、プライバシーポリシー
  get "pages/privacy_policy", to: "pages#privacy_policy", as: "privacy_policy"
  get "pages/terms_of_service", to: "pages#terms_of_service", as: "terms_of_service"
end

app/models/post.rb
class Post < ApplicationRecord
  # 値が空でないこと・最大30文字以下であること
  validates :title, presence: { message: "を入力してください" }, length: { maximum: 30, message: "は30文字以内で入力してください" }
  # 値が空でないこと・最大250文字以下であること
  validates :body, presence: { message: "を入力してください" }, length: { maximum: 250, message: "は270文字以内で入力してください" }
  # 画像が投稿されていること
  validates :post_image_url, presence: true

  belongs_to :user
  mount_uploader :post_image, PostImageUploader
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_ogp, only: [:show]

  def index
    @posts = Post.includes(:user).page(params[:page]).per(20)
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)

    Rails.logger.info "post_params: #{post_params.inspect}"

    if @post.save
      redirect_to posts_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @post = Post.find_by(id: params[:id])
    if @post.nil?
      flash[:aleat] = "お探しの投稿はありません"
      redirect_to posts_path
    end
  end

  def edit
    @post = current_user.posts.find(params[:id])
  end

  def update
    @post = current_user.posts.find(params[:id])
    if @post.update(post_params)
      redirect_to post_path(@post), success: "投稿を更新しました"
    else
      flash.now[:danger] = "更新出来ませんでした"
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    post = current_user.posts.find(params[:id])
    post.destroy!
    redirect_to posts_path, success: "投稿を削除しました", status: :see_other
  end

    private

  def post_params
    params.require(:post).permit(:title, :body, :post_image, :post_image_cache)
  end

  def set_ogp
    @post = Post.find(params[:id])
    @ogp = {
      title: @post.title,
      description: @post.body.truncate(100),
      image: @post.post_image.url || asset_path("default-ogp.png"),
      url: request.original_url
    }
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with model: @post, class: "space-y-6" do |form| %>
  <%= render 'shared/error_messages', object: form.object %>
  <!-- タイトル入力 -->
  <div>
    <%= form.label :title, "お酒名", class: "block text-lg font-medium text-gray-700" %>
    <%= form.text_field :title, placeholder: "投稿したいお酒を書こう", class: "mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500" %>
  </div>
  <!-- 本文入力 -->
  <div>
    <%= form.label :body, "コメント", class: "block text-lg font-medium text-gray-700" %>
    <%= form.text_area :body, rows: "10", placeholder: "どんなお酒か教えて！", class: "mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500" %>
  </div>
  <!-- 画像アップロード -->
  <div>
    <%= form.label :post_image, "お酒の写真", class: "block text-lg font-medium text-gray-700" %>
    <%= form.file_field :post_image, accept: "image/*", class: "mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500" %>
    <%= form.hidden_field :post_image_cache %>
    </div>
  <!-- 送信ボタン -->
  <div>
    <%= form.submit "投稿する", class: "inline-flex items-center px-4 py-2 border border-transparent text-lg font-medium rounded-md shadow-sm text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="post-id-<%= post.id %>" class="bg-white shadow-md rounded-lg overflow-hidden flex">
  <!-- 画像 -->
  <div class="w-48 h-48 flex-shrink-0">
    <%= link_to post_path(post), class: "block" do %>
      <%= image_tag post.post_image.url.presence || "/assets/post_placeholder.png", class: "w-48 h-48 object-cover" %>
    <% end %>
  </div>
  <!-- コンテンツ -->
  <div class="p-4 flex-1">
    <div class="flex items-center justify-between">
      <!-- タイトル -->
      <h4 class="text-lg font-bold">
        <%= link_to post.title, post_path(post), class: "text-gray-800 hover:text-gray-600" %>
      </h4>
      <!-- 共有、編集、削除 -->
      <% if current_user.own?(post) %>
        <div class="flex space-x-2">
          <!-- 共有ボタン -->
          <% share_url = post_url(post) %>
          <% share_text = "#{post.title} - #{post.body.truncate(50)}" %>
          <a href="https://twitter.com/intent/tweet?url=<%= URI.encode_www_form_component(share_url) %>&text=<%= URI.encode_www_form_component(share_text) %>" 
            target="_blank" 
            class="text-gray-500 hover:text-gray-700">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4">
              <path stroke-linecap="round" stroke-linejoin="round" d="M6 12 3.269 3.125A59.769 59.769 0 0 1 21.485 12 59.768 59.768 0 0 1 3.27 20.875L5.999 12Zm0 0h7.5" />
            </svg>
          </a>
          <!-- 編集ボタン -->
          <%= link_to edit_post_path(post), id: "button-edit-#{post.id}", class: "text-gray-500 hover:text-gray-700" do %>
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4">
              <path stroke-linecap="round" stroke-linejoin="round" d="m16.862 4.487 1.687-1.688a1.875 1.875 0 1 1 2.652 2.652L6.832 19.82a4.5 4.5 0 0 1-1.897 1.13l-2.685.8.8-2.685a4.5 4.5 0 0 1 1.13-1.897L16.863 4.487Zm0 0L19.5 7.125" />
            </svg>
          <% end %>
          <!-- 削除ボタン -->
          <%= link_to post_path(post), id: "button-delete-#{post.id}", data: { turbo_method: :delete, turbo_confirm: "削除しますか？" }, class: "text-gray-500 hover:text-gray-700" do %>
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4">
              <path stroke-linecap="round" stroke-linejoin="round" d="m14.74 9-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 0 1-2.244 2.077H8.084a2.25 2.25 0 0 1-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 0 0-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 0 1 3.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 0 0-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 0 0-7.5 0" />
            </svg>
          <% end %>
        </div>
      <% end %>
    </div>
    <!-- 本文 -->
    <p class="mt-4 text-gray-700 leading-relaxed"><%= simple_format(post.body.truncate(73, omission: '...')) %></p>
    <!-- ユーザー、日付 -->
    <ul class="text-sm text-gray-600 mt-2">
      <li class="flex items-center">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
          <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 6a3.75 3.75 0 1 1-7.5 0 3.75 3.75 0 0 1 7.5 0ZM4.501 20.118a7.5 7.5 0 0 1 14.998 0A17.933 17.933 0 0 1 12 21.75c-2.676 0-5.216-.584-7.499-1.632Z" />
        </svg>
        <%= post.user.name %>
      </li>
      <li class="flex items-center mt-1">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
          <path stroke-linecap="round" stroke-linejoin="round" d="M12 6v6h4.5m4.5 0a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
        </svg>
        <%= l post.created_at, format: :long %>
      </li>
    </ul>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="container mx-auto pt-5">
  <div class="mb-3">
    <div class="max-w-4xl mx-auto">
      <h1 class="text-2xl font-bold mb-6"><%= "投稿編集" %></h1>
      <%= render "form", post: @post %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container mx-auto pt-5">
  <div class="mb-3">
    <!-- 投稿一覧 -->
    <h1 class="text-2xl font-bold mb-6">投稿一覧</h1>
    <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
      <% if @posts.present? %>
        <%= render @posts %> 
      <% else %>
        <div class="text-center col-span-full text-gray-600">投稿がありません</div>
      <% end %>
    </div>
    <div class="mt-6 text-center">
      <%= paginate @posts %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container mx-auto pt-5">
  <div class="mb-3">
    <div class="max-w-4xl mx-auto">
      <h1 class="text-2xl font-bold mb-6">投稿作成</h1>
      <%= render "form", post: @post %> 
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<!-- <% content_for :title, @post.title %>
<% content_for :og_title, @post.title %>
<% content_for :og_description, @post.body %>
<% content_for :og_url, request.original_url %> -->
<div class="container mx-auto pt-5">
  <div class="mb-3">
    <div class="max-w-4xl mx-auto">
      <h1 class="text-2xl font-bold mb-5">投稿詳細</h1>
      <article class="bg-white shadow rounded-lg overflow-hidden flex flex-col">
        <!-- 画像 -->
        <div class="w-full h-full flex-shrink-0">
          <%= image_tag @post.post_image_url, class: "w-full h-full object-cover rounded-md" %>
        </div>
        <!-- タイトル、詳細情報 -->
        <div class="p-4 flex-1">
          <div class="flex items-center justify-between">
            <h3 class="text-lg font-semibold mb-2"><%= @post.title %></h3>
            <% if current_user.own?(@post) %>
              <div class="flex justify-end space-x-4">
                <!-- シェアボタン -->
                <% share_url = post_url(@post) %>
                <% share_text = "#{@post.title} - #{@post.body.truncate(50)}" %>
                <a href="https://twitter.com/intent/tweet?url=<%= URI.encode_www_form_component(share_url) %>&text=<%= URI.encode_www_form_component(share_text) %>" 
                  target="_blank" 
                  class="text-gray-500 hover:text-gray-700">
                  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M6 12 3.269 3.125A59.769 59.769 0 0 1 21.485 12 59.768 59.768 0 0 1 3.27 20.875L5.999 12Zm0 0h7.5" />
                  </svg>
                </a>
                <!-- 編集ボタン -->
                <%= link_to edit_post_path(@post), id: "button-edit-#{@post.id}", class: "text-gray-500 hover:text-gray-700" do %>
                  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
                    <path stroke-linecap="round" stroke-linejoin="round" d="m16.862 4.487 1.687-1.688a1.875 1.875 0 1 1 2.652 2.652L6.832 19.82a4.5 4.5 0 0 1-1.897 1.13l-2.685.8.8-2.685a4.5 4.5 0 0 1 1.13-1.897L16.863 4.487Zm0 0L19.5 7.125" />
                  </svg>
                <% end %>
                <!-- 削除ボタン -->
                <%= link_to post_path(@post), id: "button-delete-#{@post.id}", data: { turbo_method: :delete, turbo_confirm: "削除しますか？" }, class: "text-gray-500 hover:text-gray-700" do %>
                  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
                   <path stroke-linecap="round" stroke-linejoin="round" d="m14.74 9-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 0 1-2.244 2.077H8.084a2.25 2.25 0 0 1-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 0 0-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 0 1 3.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 0 0-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 0 0-7.5 0" />
                  </svg>
                <% end %>
              </div>
            <% end %>
          </div>
          <!-- 本文 -->
          <p class="mt-4 text-gray-700 leading-relaxed"><%= simple_format(@post.body) %></p>
          <!-- ユーザー、日付 -->
          <ul class="flex text-sm text-gray-600 space-x-4 mb-4">
            <li><%= "#{@post.user.name}" %></li>
            <li><%= l @post.created_at, format: :long %></li>
          </ul>
        </div>
      </article>
    </div>
  </div>
</div>