config/routes.rb
Rails.application.routes.draw do
  root "static_pages#top"
  # ユーザー処理
  resources :users, only: %i[new create show edit update]
  resource :mypage, only: %i[show edit update]
  # 投稿一覧、投稿作成
  resources :posts, only: %i[index new create show edit update destroy]
  # カテゴリーページ
  resources :categories, only: %i[show], param: :category
  resources :drinks, only: %i[show]
  # ログインアウト処理
  get "login", to: "user_sessions#new"
  post "login", to: "user_sessions#create"
  delete "logout", to: "user_sessions#destroy"
  delete "/logout", to: "user_sessions#destroy"
  # Google認証
  get "/auth/:provider/callback", to: "user_sessions#google_auth"
  get "/auth/failure", to: redirect("/")
  # 管理者専用設定
  namespace :admin do
    resources :drinks, only: %i[index new create edit update]
  end
  # Drinkのブックマーク設定
  resources :bookmarks, only: %i[create destroy]
  resources :drinks, only: %i[index new create show edit update destroy] do
    collection do
      get :bookmarks
    end
  end
  # 利用規約、プライバシーポリシー
  get "pages/privacy_policy", to: "pages#privacy_policy", as: "privacy_policy"
  get "pages/terms_of_service", to: "pages#terms_of_service", as: "terms_of_service"
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts
  has_many :drinks

  ransack_alias :name_cont, :name

  def display_name
    translations = {
      "beer" => "ビール",
      "wine" => "ワイン",
      "nihonshu" => "日本酒",
      "shochu" => "焼酎",
      "cocktail" => "カクテル",
      "etc" => "その他"
    }
    translations[name] || name # 該当する名前がない場合はそのまま返す
  end

  def category_name
    case name
    when "ビール"
      "ビール"
    when "ワイン"
      "ワイン"
    when "日本酒"
      "日本酒"
    when "焼酎"
      "焼酎"
    when "カクテル"
      "カクテル"
    when "etc"
      "その他"
    else
      "不明"
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  skip_before_action :require_login, only: %i[show]
  
  def show
    category_name = params[:category].to_s
    if category_name.blank?
      redirect_to root_path, alert: "カテゴリーが見つかりませんでした" and return
    end

    @drinks = Drink.where(category: category_name, is_admin: true)
    @bookmark_drinks = current_user&.bookmarked_drinks || []
    @category = Category.find_by(name: params[:category])
    @categories = Category.page(params[:page]).per(20)
    @drinks = @category.drinks if @category.present?
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_bookmark.html.erb
<%= link_to bookmarks_path(drink_id: drink.id), id: "bookmark-button-for-drink-#{drink.id}", data: { turbo_method: :post } do %>
  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
    <path stroke-linecap="round" stroke-linejoin="round" d="M17.593 3.322c1.1.128 1.907 1.077 1.907 2.185V21L12 17.25 4.5 21V5.507c0-1.108.806-2.057 1.907-2.185a48.507 48.507 0 0 1 11.186 0Z" />
  </svg>
<% end %>

app/views/categories/_bookmark_buttons.html.erb
<div class='ml-auto'>
  <% if current_user&.bookmark?(drink) %>
    <%= render "categories/unbookmark", { drink: drink } %>
  <% elsif current_user %>
    <%= render "categories/bookmark", { drink: drink } %>
  <% else %>
    <link_to "ログインしてブックマーク", login_path, class: "text-blue-500 underline" %>
  <% end %>
</div>

app/views/categories/_unbookmark.html.erb
<%= link_to bookmark_path(current_user.bookmarks.find_by(drink_id: drink.id)), id: "unbookmark-button-for-drink-#{drink.id}", data: { turbo_method: :delete } do %>
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-5 h-5">
    <path fill-rule="evenodd" d="M6.32 2.577a49.255 49.255 0 0 1 11.36 0c1.497.174 2.57 1.46 2.57 2.93V21a.75.75 0 0 1-1.085.67L12 18.089l-7.165 3.583A.75.75 0 0 1 3.75 21V5.507c0-1.47 1.073-2.756 2.57-2.93Z" clip-rule="evenodd" />
  </svg>
<% end %>

app/views/categories/show.html.erb
<div class="container mx-auto pt-5">
  <div class="mb-3">
    <!-- カテゴリー名 -->
    <h2 class="text-2xl font-bold mb-4">
      <%= Category.find_by(id: params[:category])&.category_name %>一覧
    </h2>

    <!-- 投稿一覧 -->
    <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
      <% if @drinks.present? %>
        <% @drinks.each do |drink| %>
          <div id="drink-id-<%= drink.id %>" class="bg-white shadow-md rounded-lg overflow-hidden flex">
            <!-- 画像 -->
            <div class="w-48 h-48 flex-shrink-0">
              <%= link_to drink_path(drink), class: "block" do %>
                <%= image_tag drink.drink_image_url, class: "w-48 h-48 object-cover" %>
              <% end %>
            </div>

            <!-- コンテンツ -->
            <div class="p-4 flex-1">
              <div class="flex items-center justify-between">
                <!-- タイトル -->
                <h4 class="text-lg font-bold">
                  <%= link_to drink.name, drink_path(drink), class: "text-gray-800 hover:text-gray-600" %>
                </h4>
                <div class="flex space-x-2">
                  <% if current_user&.own?(drink) %>
                    <!-- 共有ボタン -->
                    <% share_url = drink_url(drink) %>
                    <% share_text = "#{drink.name} - #{drink.description}" %>
                    <a href="https://twitter.com/intent/tweet?url=<%= URI.encode_www_form_component(share_url) %>&text=<%= URI.encode_www_form_component(share_text) %>" 
                      target="_blank" 
                      class="text-gray-500 hover:text-gray-700">
                      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M6 12 3.269 3.125A59.769 59.769 0 0 1 21.485 12 59.768 59.768 0 0 1 3.27 20.875L5.999 12Zm0 0h7.5" />
                      </svg>
                    </a>
                    <!-- 編集ボタン -->
                    <%= link_to edit_admin_drink_path(drink), id: "button-edit-#{drink.id}", class: "text-gray-500 hover:text-gray-700" do %>
                      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4">
                        <path stroke-linecap="round" stroke-linejoin="round" d="m16.862 4.487 1.687-1.688a1.875 1.875 0 1 1 2.652 2.652L6.832 19.82a4.5 4.5 0 0 1-1.897 1.13l-2.685.8.8-2.685a4.5 4.5 0 0 1 1.13-1.897L16.863 4.487Zm0 0L19.5 7.125" />
                      </svg>
                    <% end %>
                    <!-- 削除ボタン -->
                    <%= link_to drink_path(drink), id: "button-delete-#{drink.id}", data: { turbo_method: :delete, turbo_confirm: "削除しますか？" }, class: "text-gray-500 hover:text-gray-700" do %>
                      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4">
                        <path stroke-linecap="round" stroke-linejoin="round" d="m14.74 9-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 0 1-2.244 2.077H8.084a2.25 2.25 0 0 1-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 0 0-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 0 1 3.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 0 0-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 0 0-7.5 0" />
                      </svg>
                    <% end %>
                  <% else %>
                    <%= render "bookmark_buttons", { drink: drink } %>
                  <% end %>
                </div>
              </div>
              <!-- 本文 -->
              <p class="mt-4 text-gray-700 leading-relaxed"><%= simple_format(drink.description) %></p>
              <!-- アルコール度数 -->
              <ul class="text-sm text-gray-600">
                アルコール度数: <%= drink.alcohol %>%
              </ul>
              <!-- 作り方 -->
              <p class="mt-4 text-gray-700 leading-relaxed">
                <%= drink.mixing_instructions %>
              </p>
            </div>
          </div>
        <% end %>
      <% else %>
        <div class="text-center col-span-full text-gray-600">投稿がありません</div>
      <% end %>
    </div>
    <div class="mt-6">
      <%= paginate @categories %>
    </div>
  </div>
</div>